# Generated by Django 2.2.21 on 2022-03-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follow_by',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follow_to',
            field=models.TextField(default=''),
        ),
    ]
