# Generated by Django 2.1.5 on 2022-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220319_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follow_to',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follower_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_muted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='like_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
